# Cloud Build configuration for GroeimetAI
# Just builds and deploys - env vars are set directly in Cloud Run

steps:
  # Step 1: Build Docker image (BuildKit enabled for cache mounts)
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build'
    env:
      - 'DOCKER_BUILDKIT=1'
    args:
      - 'build'
      - '-t'
      - 'europe-west1-docker.pkg.dev/${PROJECT_ID}/groeimetai-app/groeimetai-app:${COMMIT_SHA}'
      - '-t'
      - 'europe-west1-docker.pkg.dev/${PROJECT_ID}/groeimetai-app/groeimetai-app:latest'
      - '.'

  # Step 2: Push images
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Push'
    args:
      - 'push'
      - '--all-tags'
      - 'europe-west1-docker.pkg.dev/${PROJECT_ID}/groeimetai-app/groeimetai-app'

  # Step 3: Deploy to Cloud Run (env vars already configured in Cloud Run)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    id: 'Deploy'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'groeimetai-app'
      - '--platform=managed'
      - '--image=europe-west1-docker.pkg.dev/${PROJECT_ID}/groeimetai-app/groeimetai-app:${COMMIT_SHA}'
      - '--region=europe-west1'
      - '--quiet'

images:
  - 'europe-west1-docker.pkg.dev/${PROJECT_ID}/groeimetai-app/groeimetai-app:${COMMIT_SHA}'
  - 'europe-west1-docker.pkg.dev/${PROJECT_ID}/groeimetai-app/groeimetai-app:latest'

options:
  logging: CLOUD_LOGGING_ONLY
