steps:
  # Build the Docker image with NEXT_PUBLIC_* variables
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--build-arg'
      - 'NEXT_PUBLIC_FIREBASE_API_KEY=${_NEXT_PUBLIC_FIREBASE_API_KEY}'
      - '--build-arg'
      - 'NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=${_NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN}'
      - '--build-arg'
      - 'NEXT_PUBLIC_FIREBASE_PROJECT_ID=${_NEXT_PUBLIC_FIREBASE_PROJECT_ID}'
      - '--build-arg'
      - 'NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=${_NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET}'
      - '--build-arg'
      - 'NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=${_NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID}'
      - '--build-arg'
      - 'NEXT_PUBLIC_FIREBASE_APP_ID=${_NEXT_PUBLIC_FIREBASE_APP_ID}'
      - '--build-arg'
      - 'NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID=${_NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID}'
      - '--build-arg'
      - 'NEXT_PUBLIC_GEMINI_API_KEY=${_NEXT_PUBLIC_GEMINI_API_KEY}'
      - '--build-arg'
      - 'NEXT_PUBLIC_APP_URL=${_NEXT_PUBLIC_APP_URL}'
      - '--build-arg'
      - 'NEXT_PUBLIC_GOOGLE_MAPS_API_KEY=${_NEXT_PUBLIC_GOOGLE_MAPS_API_KEY}'
      - '-t'
      - 'europe-west1-docker.pkg.dev/${PROJECT_ID}/groeimetai-app/groeimetai-app:${COMMIT_SHA}'
      - '-t'
      - 'europe-west1-docker.pkg.dev/${PROJECT_ID}/groeimetai-app/groeimetai-app:latest'
      - '.'

  # Push the images
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'europe-west1-docker.pkg.dev/${PROJECT_ID}/groeimetai-app/groeimetai-app:${COMMIT_SHA}'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'europe-west1-docker.pkg.dev/${PROJECT_ID}/groeimetai-app/groeimetai-app:latest'

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'groeimetai-app'
      - '--image'
      - 'europe-west1-docker.pkg.dev/${PROJECT_ID}/groeimetai-app/groeimetai-app:${COMMIT_SHA}'
      - '--region'
      - 'europe-west1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--set-env-vars'
      - 'NODE_ENV=production,FIREBASE_PROJECT_ID=${_FIREBASE_PROJECT_ID},FIREBASE_CLIENT_EMAIL=${_FIREBASE_CLIENT_EMAIL},FIREBASE_STORAGE_BUCKET=${_FIREBASE_STORAGE_BUCKET},NEXT_PUBLIC_APP_URL=${_NEXT_PUBLIC_APP_URL},SMTP_HOST=${_SMTP_HOST},SMTP_PORT=${_SMTP_PORT},SMTP_USER=${_SMTP_USER},GEMINI_API_KEY=${_GEMINI_API_KEY}'
      - '--set-secrets'
      - 'FIREBASE_PRIVATE_KEY=firebase-private-key:latest,SMTP_PASS=smtp-password:latest,PINECONE_API_KEY=pinecone-api-key:latest,OPENAI_API_KEY=openai-api-key:latest'
      - '--min-instances'
      - '1'
      - '--max-instances'
      - '10'
      - '--memory'
      - '1Gi'
      - '--cpu'
      - '1'
      - '--timeout'
      - '300'
      - '--port'
      - '8080'

# Substitution variables - set these in Cloud Build trigger
substitutions:
  _NEXT_PUBLIC_FIREBASE_API_KEY: ''
  _NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: ''
  _NEXT_PUBLIC_FIREBASE_PROJECT_ID: ''
  _NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET: ''
  _NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID: ''
  _NEXT_PUBLIC_FIREBASE_APP_ID: ''
  _NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID: ''
  _NEXT_PUBLIC_GEMINI_API_KEY: ''
  _NEXT_PUBLIC_APP_URL: ''
  _NEXT_PUBLIC_GOOGLE_MAPS_API_KEY: ''
  _FIREBASE_PROJECT_ID: ''
  _FIREBASE_CLIENT_EMAIL: ''
  _FIREBASE_STORAGE_BUCKET: ''
  _SMTP_HOST: ''
  _SMTP_PORT: ''
  _SMTP_USER: ''
  _GEMINI_API_KEY: ''

options:
  logging: CLOUD_LOGGING_ONLY

images:
  - 'europe-west1-docker.pkg.dev/${PROJECT_ID}/groeimetai-app/groeimetai-app:${COMMIT_SHA}'
  - 'europe-west1-docker.pkg.dev/${PROJECT_ID}/groeimetai-app/groeimetai-app:latest'
